// export const FETCH_MARKET_BEGIN = 'FETCH_MARKET_BEGIN';
// export const FETCH_MARKET_SUCCESS = 'FETCH_MARKET_SUCCESS';
// export const FETCH_MARKET_FAILURE = 'FETCH_MARKET_FAILURE';


// export const FETCH_VOLUNTEERS_BEGIN = 'FETCH_VOLUNTEERS_BEGIN';
// export const FETCH_VOLUNTEERS_SUCCESS = 'FETCH_VOLUNTEERS_SUCCESS';


// export const FETCH_PRODUCTS_BEGIN = 'FETCH_PRODUCTS_BEGIN';
// export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';