export const ADD_SIGNUP_BEGIN = 'ADD_SIGNUP_BEGIN';
export const ADD_SIGNUP_SUCCESS = 'ADD_SIGNUP_SUCCESS';
export const ADD_SIGNUP_FAILURE = 'ADD_SIGNUP_FAILURE';

export const ADD_TODO = "ADD_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const SET_FILTER = "SET_FILTER";